[variables]
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x", "yarn"]

[phases.build]
cmds = [
  "yarn install --frozen-lockfile",
  "npm install",
  "npm run build"
]

[start]
cmd = "npm run preview -- --host 0.0.0.0"
