[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs-20_x", "yarn"]

[phases.build]
cmds = [
  "yarn install --frozen-lockfile",
  "npm install",
  "npm run build"
]

[start]
cmd = "npm run preview -- --host 0.0.0.0"
