services:
  - name: python-sjm
    type: web
    env: python
    buildCommand: cd python-sjm && pip install -r requirements.txt
    startCommand: cd python-sjm && gunicorn app:app
    envVars:
      - key: PORT
        value: 7900
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: CLIENT_URL
        fromService:
          name: client
          type: web
          property: url

  - name: server
    type: web
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node app.js
    envVars:
      - key: PORT
        value: 7800
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URI
        sync: false
      - key: CLIENT_URL
        fromService:
          name: client
          type: web
          property: url

  - name: client
    type: web
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run preview -- --host 0.0.0.0
    envVars:
      - key: VITE_API_URL
        fromService:
          name: server
          type: web
          property: url
          append: /api
      - key: VITE_PYTHON_API_URL
        fromService:
          name: python-sjm
          type: web
          property: url